import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#410002",
        "secondary-fixed-dim": "#e0c298",
        "on-error-container": "#93000a",
        "surface-container-high": "#e1e8fd",
        "surface-tint": "#5f5e60",
        "on-secondary-fixed-variant": "#584323",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1c1b1d",
        "background": "#f9f9ff",
        "surface-variant": "#dce2f7",
        "on-error": "#ffffff",
        "secondary-container": "#fedeb2",
        "inverse-surface": "#293040",
        "on-surface-variant": "#47464a",
        "primary-fixed-dim": "#c8c6c8",
        "on-primary-container": "#858386",
        "on-primary-fixed-variant": "#474649",
        "error-container": "#ffdad6",
        "primary-fixed": "#e5e1e4",
        "on-secondary-fixed": "#281800",
        "tertiary": "#000000",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "primary-dark": "#0A0A0C",
        "inverse-primary": "#c8c6c8",
        "error": "#ba1a1a",
        "surface-container-highest": "#dce2f7",
        "on-tertiary-container": "#f63a35",
        "on-tertiary": "#ffffff",
        "surface-container": "#e9edff",
        "inverse-on-surface": "#edf0ff",
        "surface-bright": "#f9f9ff",
        "outline": "#78767b",
        "outline-variant": "#c8c5ca",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb4ab",
        "on-secondary-container": "#78603e",
        "tertiary-fixed": "#ffdad6",
        "on-background": "#141b2b",
        "surface": "#f9f9ff",
        "surface-dim": "#d3daef",
        "secondary": "#725b38",
        "on-surface": "#141b2b",
        "tertiary-container": "#410002",
        "on-tertiary-fixed-variant": "#93000b",
        "surface-container-low": "#f1f3ff",
        "secondary-fixed": "#fedeb2",
        "primary-container": "#1c1b1d",
        "accent-luxury": "#C5A880",
        "accent-gold": "#C5A880",
        "accent-crimson": "#DC2626",
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "price-strike": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "label-badge": ["Montserrat", "sans-serif"],
        "headline-xl-mobile": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "display-hero-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "price-lg": ["Montserrat", "sans-serif"],
        "display-hero": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        heading: ["Montserrat", "sans-serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
        arabic: ["Cairo", "sans-serif"],
      },
      letterSpacing: {
        widest: "0.25em",
        tracked: "0.12em",
      },
    },
  },
  plugins: [],
};
export default config;
